"""HTML report generator"""
import asyncio
from pathlib import Path
from datetime import datetime
from typing import Dict, Any
from loguru import logger

try:
    from jinja2 import Template
except ImportError:
    Template = None

class HTMLReportGenerator:
    def __init__(self, config):
        self.config = config
    
    async def generate(self, data: Dict, output_path) -> Any:
        logger.info(f"Generating HTML report: {output_path}")
        
        html_template = """
<!DOCTYPE html>
<html>
<head>
    <title>AutoPenTest Report - {{ data.target }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }
        h1 { color: #d32f2f; border-bottom: 3px solid #d32f2f; padding-bottom: 10px; }
        h2 { color: #1976d2; margin-top: 30px; }
        .summary { background: #e3f2fd; padding: 20px; border-radius: 5px; margin: 20px 0; }
        .critical { color: #d32f2f; font-weight: bold; }
        .high { color: #f57c00; font-weight: bold; }
        .medium { color: #fbc02d; font-weight: bold; }
        .low { color: #388e3c; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #1976d2; color: white; }
        tr:hover { background: #f5f5f5; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🛡️ AutoPenTest Security Assessment Report</h1>
        
        <div class="summary">
            <h2>Executive Summary</h2>
            <p><strong>Target:</strong> {{ data.target }}</p>
            <p><strong>Date:</strong> {{ timestamp }}</p>
            <p><strong>Total Vulnerabilities:</strong> {{ data.vulnerabilities|length }}</p>
        </div>
        
        <h2>Findings</h2>
        <table>
            <tr>
                <th>Severity</th>
                <th>Vulnerability</th>
                <th>Description</th>
                <th>Recommendation</th>
            </tr>
            {% for vuln in data.vulnerabilities %}
            <tr>
                <td class="{{ vuln.severity }}">{{ vuln.severity|upper }}</td>
                <td>{{ vuln.name }}</td>
                <td>{{ vuln.description[:100] }}...</td>
                <td>{{ vuln.solution or 'Review and patch' }}</td>
            </tr>
            {% endfor %}
        </table>
        
        <div class="footer">
            <p>Generated by AutoPenTest | {{ timestamp }}</p>
            <p>⚠️ This report contains sensitive security information. Handle with care.</p>
        </div>
    </div>
</body>
</html>
        """
        
        try:
            if Template:
                template = Template(html_template)
                html = template.render(data=data, timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
            else:
                html = html_template.replace('{{ data.target }}', str(data.get('target', 'Unknown')))
            
            Path(output_path).write_text(html, encoding='utf-8')
            logger.success(f"HTML report generated: {output_path}")
            return output_path
        except Exception as e:
            logger.error(f"HTML generation failed: {e}")
            return None
    
    async def generate_from_result(self, assessment_result, output_path):
        data = {
            'target': assessment_result.target,
            'vulnerabilities': assessment_result.vulnerabilities
        }
        return await self.generate(data, output_path)
