"""Markdown report generator"""
import asyncio
from pathlib import Path
from datetime import datetime
from typing import Dict, Any
from loguru import logger

class MarkdownGenerator:
    def __init__(self, config):
        self.config = config
    
    async def generate(self, data: Dict, output_path) -> Any:
        logger.info(f"Generating Markdown report: {output_path}")
        
        md = f"""# 🛡️ AutoPenTest Security Assessment Report

## Executive Summary

**Target:** {data.get('target', 'Unknown')}  
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Total Vulnerabilities:** {len(data.get('vulnerabilities', []))}

---

## Findings

"""
        
        # Group by severity
        vulns = data.get('vulnerabilities', [])
        for severity in ['critical', 'high', 'medium', 'low', 'info']:
            severity_vulns = [v for v in vulns if getattr(v, 'severity', 'info').lower() == severity]
            if severity_vulns:
                md += f"\n### {severity.upper()} Severity ({len(severity_vulns)})\n\n"
                for vuln in severity_vulns:
                    name = getattr(vuln, 'name', 'Unknown')
                    desc = getattr(vuln, 'description', 'No description')
                    solution = getattr(vuln, 'solution', 'Review and patch')
                    md += f"#### {name}\n\n"
                    md += f"**Description:** {desc}\n\n"
                    md += f"**Recommendation:** {solution}\n\n"
                    md += "---\n\n"
        
        md += f"""
## Report Information

- **Generated by:** AutoPenTest v1.0.0
- **Timestamp:** {datetime.now().isoformat()}

⚠️ **Confidential:** This report contains sensitive security information.
"""
        
        try:
            Path(output_path).write_text(md, encoding='utf-8')
            logger.success(f"Markdown report generated: {output_path}")
            return output_path
        except Exception as e:
            logger.error(f"Markdown generation failed: {e}")
            return None
